// update with:
// cog -P -r palavras.js
const PALAVRAS = [
  //[[[cog
  //words = sorted(w for w in open('palavras.txt').read().splitlines())
  //for w in words:
  //    print("%r," % w)
  //]]]
  'Abelha',
  'Amargo',
  'Amor',
  'Apito',
  'Aplausos',
  'Arco íris',
  'Artista',
  'Astronauta',
  'Açúcar',
  'Bailarina',
  'Banana',
  'Barata',
  'Basquete',
  'Bata',
  'Bateria',
  'Bebê',
  'Bebê Yoda',
  'Beliche',
  'Biblioteca',
  'Bilhete',
  'Bob Esponja',
  'Bola de neve',
  'Bolha',
  'Bolinho',
  'Borboleta',
  'Buraco negro',
  'Cachorro',
  'Cadeado',
  'Cadeira',
  'Calculadora',
  'Capivara',
  'Caranguejo',
  'Carteira',
  'Carteiro',
  'Casca de banana',
  'Castelo de Areia',
  'Cavalo',
  'Cego',
  'Chimpanzé',
  'Cigarro',
  'Cinderela',
  'Coala',
  'Coelho',
  'Colméia',
  'Coral',
  'Cortador de grama',
  'Cápsula',
  'Debate',
  'Deserto',
  'Dicionário',
  'Disney World',
  'Duende',
  'EUA',
  'Eclipse',
  'Elefante',
  'Escorpião',
  'Escoteiro',
  'Escova de dentes',
  'Esquilo',
  'Estação de trem',
  'Estojo',
  'Estrada',
  'Estrela',
  'Estátua',
  'Fazenda',
  'Fogos de artifício',
  'Fones de ouvido',
  'Formiga',
  'Frio',
  'Futebol',
  'Fósforo',
  'Galinha',
  'Gato',
  'Girafa',
  'Golfinho',
  'Grilo',
  'Guirlanda',
  'Guitarra',
  'Harry Potter',
  'Havaí',
  'Hematoma',
  'Hipopótamo',
  'Hospital',
  'Iglu',
  'Infinito',
  'Internet',
  'Jacaré',
  'Japão',
  'Jogo de tabuleiro',
  'Justin Bieber',
  'Ketchup',
  'Ladrão',
  'Las Vegas',
  'Leão',
  'Limão',
  'Livro',
  'Lixo',
  'Lustre',
  'Lápis',
  'Maca',
  'Marte',
  'Martelo',
  'Massagem',
  'Micróbio',
  'Montanhas',
  'Morango',
  'Máquina de lavar',
  'Máquina do tempo',
  'Médico',
  'México',
  'Mímico',
  'Nata',
  'Nevasca',
  'Névoa',
  'Olimpíadas',
  'Ornitorrinco',
  'Padeiro',
  'Panda',
  'Paraíso',
  'Paris',
  'Pasta de dentes',
  'Pescador',
  'Peteca',
  'Pikachu',
  'Pincel',
  'Pintor',
  'Pirata',
  'Piscina',
  'Planeta terra',
  'Policial',
  'Polo Norte',
  'Porco',
  'Praia',
  'Prancha de surfe',
  'Professor',
  'Protetor solar',
  'Rainha Elizabeth',
  'Ramalhete',
  'Rato',
  'Relógio',
  'Robin Hood',
  'Romance',
  'Saco de dormir',
  'Sacola',
  'Salamandra',
  'Sapo',
  'Semente',
  'Serpente',
  'Shrek',
  'Sinuca',
  'Skate',
  'Sombra',
  'Super homem',
  'Sótão',
  'Templo',
  'Tigre',
  'Tiranossauro Rex',
  'Trem',
  'Tênis',
  'Ukulelê',
  'Vampiro',
  'Vaqueiro',
  'Veado',
  'Vela',
  'Verão',
  'Vespa',
  'Violino',
  'Violoncelo',
  'Vitória',
  'Waffles',
  'Xadrez',
  'crosta',
  'roda gigante',
  'Águia',
  'Ódio',
  //[[[end]]]
]
